puddle/conversation/urls.py
from . import views
from django.urls import path

app_name = 'conversation'

urlpatterns = [
    path('', views.Inbox, name='inbox'),
    path('<int:pk>/', views.MessageDetail, name='detail'),
    path('new/<int:item_pk>/', views.NewConversation, name='new'),
]

puddle/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from . import views
from .forms import LoginForm

app_name = "core"

urlpatterns = [
    path("", views.Index, name='index'),
    path("contact/", views.Contact, name="contact"),
    path("signup/", views.SignUp, name="signup"),
    path("login/", auth_view.LoginView.as_view(template_name="core/login.html",authentication_form=LoginForm), name="login"),
]

puddle/dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
    path('', views.Dashboard, name='dashboard'),
]

puddle/item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.ItemView, name='item_view'),
    path("<int:pk>/", views.Detail, name="detail"),
    path('new_item/', views.New_Item, name="new_item"),
    path('<int:pk>/delete/', views.Delete, name='delete'), 
    path('<int:pk>/edit/', views.Edit_Item, name='edit'),
]

puddle/puddle/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from core import views

urlpatterns = [
    path('', include("core.urls")),
    path('item/', include("item.urls")),
    path('dashboard/', include('dashboard.urls')),
    path('conversation/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

puddle/core/models.py
from django.db import models

# Create your models here.

puddle/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "Your username",
        'class': 'py-3 px-3 rounded-xl outline-teal-500 w-full ',
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Your password",
        'class': 'py-3 px-3 rounded-xl outline-teal-500 w-full ',
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", 'password1', 'password2') 

    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "Your username",
        'class': 'py-3 px-3 rounded-xl outline-teal-500 w-full ',
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        "placeholder": "Your email address",
        'class': 'py-3 px-3 rounded-xl outline-teal-500 w-full ',
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Your password",
        'class': 'py-3 px-3 rounded-xl outline-teal-500 w-full ',
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Repeat pasword",
        'class': 'py-3 px-3 rounded-xl outline-teal-500 w-full ',
    }))

puddle/core/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from item.models import Category, Item
from .forms import SignupForm
# Create your views here.

def Index(request):
    items = Item.objects.filter(is_sold=False)[:6]
    categories = Category.objects.all()
    return render(request, "core/index.html", {
        "items": items,
        "categories": categories,
    })

def Contact(request):
    return render(request, "core/contact.html")


def SignUp(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect(reverse("core:login"))
    
    else: 
        form = SignupForm()



    return render(request, 'core/signup.html', {"form": form})

puddle/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%} {% endblock %}| Puddle</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <nav class="px-6 py-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">Puddle</a>
        
        <div class="space-x-6">
            <a href="{%url 'item:new_item' %}" class="text-lg font-semibold hover:text-gray-500">New Item</a>
            <a href="{% url 'item:item_view' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>

            {% if user.is_authenticated %}
            <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 hover:bg-teal-700 text-white rounded-xl">Inbox</a>
            <a href="{% url 'dashboard:dashboard' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 hover:bg-gray-700 text-white rounded-xl">Dashboard</a>
            {% else %}
            <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 hover:bg-teal-700 text-white rounded-xl">Sign up</a>
            <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 hover:bg-gray-700 text-white rounded-xl">Log in</a>
            {% endif %}
        </div>

    </nav>
    {% block content %}
    {% endblock %}

    <footer class="px-6 py-6 mt-6 bg-gray-800 flex justify-between ">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 text-gray-400 font-semibold"> About</h3>
            <p class="text-lg text-gray-500 ">Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque do</p>
        </div>

        <div class="w-1/3">
            <h3 class="mb-5 text-gray-400 font-semibold">Menu</h3>
            <ul class="space-y-2">
                <li>
                    <a href="#" class="text-lg text-teal-400 hover:text-teal-700">About</a>
                </li>
                <li>
                    <a href="{% url 'core:contact' %}" class="text-lg text-teal-400 hover:text-teal-700">Contact</a>
                </li>
                <li>
                    <a href="#" class="text-lg text-teal-400 hover:text-teal-700">Privacy</a>
                </li>
            </ul>
        </div>
    </footer>
</body>
</html>

puddle/core/templates/core/contact.html
{% extends "core/base.html" %}

{% block title%} 
    Contact 
{% endblock%}

{% block content %}
    <h1 class="">Contact page</h1>
{% endblock %}

puddle/core/templates/core/index.html
{% extends "core/base.html" %}

{% block title%} 
    Welcome 
{% endblock%}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest Items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
            <div class="aspect-ratio">
                <a href="{% url 'item:detail' item.id %}" class="">
                    <div>
                        <img src="{{ item.item_image.url }}" alt="" class="rounded-t-xl">
                    </div>
                    
                
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{item.name}}</h2>
                        <p text-gray-500>Price: GHc {{item.price}}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>


    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
            <div>
                <a href="#">
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{category.name}}</h2>
                        <p text-gray-500>{{ category.items.count}} items </p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

puddle/core/templates/core/login.html
{% extends "core/base.html" %}

{% block title %} Log In {% endblock %}

{% block content %}
<div class="w-1/2 p-6 my-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl text-center">Log In</h1>

    <form action="." method="post" class="">
        {% csrf_token %}
        

        <div class="mb-3 ">
            <label  class="inline-block mb-2 col-span-1">Username </label>  <br>
            {{form.username}}
        </div>


        <div class="mb-3 ">
            <label  class="inline-block mb-2 ">Password </label>
            <br>
            {{form.password}}
        </div>

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form%}
                {{field.errors}}
            {% endfor %}

            {{form.non_field_errors}}
        </div>
        {% endif %}

        <button class="px-10 mt-4 w-full py-3 text-lg mx-auto bg-teal-500 hover:bg-teal-700 text-white rounded-xl">Submit</button>
    </form>
</div>
{% endblock %}

puddle/core/templates/core/signup.html
{% extends "core/base.html" %}

{% block title %} Sign Up {% endblock %}

{% block content %}
<div class="w-1/2 p-6 my-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl text-center">Sign up</h1>

    <form action="." method="post" class="">
        {% csrf_token %}
        
        {{form.non_field_errors}}

        <div class="mb-3 ">
            <label  class="inline-block mb-2 col-span-1">Username </label>  <br>
            {{form.username}}
        </div>

        <div class="mb-3 ">
            <label  class="inline-block mb-2 ">Email </label>
            <br>
            {{form.email}}
        </div>

        <div class="mb-3 ">
            <label  class="inline-block mb-2 ">Password </label>
            <br>
            {{form.password1}}
        </div>

        <div class="mb-3 ">
            <label  class="inline-block mb-2 ">Repeat password </label>
            <br>
            {{form.password2}}
        </div>

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form%}
                {{field.errors}}
            {% endfor %}

            {{form.non_field_errors}}
        </div>
        {% endif %}

        <button class="px-10 mt-4 w-full py-3 text-lg mx-auto bg-teal-500 hover:bg-teal-700 text-white rounded-xl">Submit</button>
    </form>
</div>
{% endblock %}