puddle/conversation/urls.py
from . import views
from django.urls import path

app_name = 'conversation'

urlpatterns = [
    path('', views.Inbox, name='inbox'),
    path('<int:pk>/', views.MessageDetail, name='detail'),
    path('new/<int:item_pk>/', views.NewConversation, name='new'),
]

puddle/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from . import views
from .forms import LoginForm

app_name = "core"

urlpatterns = [
    path("", views.Index, name='index'),
    path("contact/", views.Contact, name="contact"),
    path("signup/", views.SignUp, name="signup"),
    path("login/", auth_view.LoginView.as_view(template_name="core/login.html",authentication_form=LoginForm), name="login"),
]

puddle/item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.ItemView, name='item_view'),
    path("<int:pk>/", views.Detail, name="detail"),
    path('new_item/', views.New_Item, name="new_item"),
    path('<int:pk>/delete/', views.Delete, name='delete'), 
    path('<int:pk>/edit/', views.Edit_Item, name='edit'),
]

puddle/puddle/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from core import views

urlpatterns = [
    path('', include("core.urls")),
    path('item/', include("item.urls")),
    path('dashboard/', include('dashboard.urls')),
    path('conversation/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

puddle/item/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name_plural = "Categories"


class Item(models.Model):
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    item_image = models.ImageField(upload_to="item_images", blank=True, null=True)
    is_sold = models.BooleanField()
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

puddle/item/forms.py
from  django import forms
from .models import Item

Input_class = 'w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'item_image', )

        widgets = {
            'category': forms.Select(attrs = {
                'class': Input_class, 
            }), 

            'name': forms.TextInput(attrs = {
                'class': Input_class, 
            }),

            'description': forms.Textarea(attrs = {
                'class': Input_class, 
            }), 
            
            'price': forms.TextInput(attrs = {
                'class': Input_class, 
            }),

            'item_imaage': forms.FileInput(attrs = {
                'class': Input_class, 
            })
        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'item_image', 'is_sold', )

        widgets = { 
            'name': forms.TextInput(attrs = {
                'class': Input_class, 
            }),

            'description': forms.Textarea(attrs = {
                'class': Input_class, 
            }), 
            
            'price': forms.TextInput(attrs = {
                'class': Input_class, 
            }),

            'item_imaage': forms.FileInput(attrs = {
                'class': Input_class, 
            })
        }

puddle/item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Item, Category
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .forms import NewItemForm, EditItemForm
# Create your views here.

def ItemView(request):
    item = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()
    category_id = request.GET.get('category', 0)
    query = request.GET.get('query', '')

    if category_id:
        item = item.filter(category_id=category_id)

    if query:
        item = item.filter(Q(name__icontains = query) | Q(description__icontains=query))

    return render(request, 'item/item.html', {
        'items': item,
        'query': query,
        'categories': categories,
        'category_id': int(category_id)
    })

def Detail(request, pk):
    item = get_object_or_404(Item, id=pk)
    related_items = Item.objects.filter(category=item.category, is_sold = False).exclude(pk=pk)[:5]

    return render(request, "item/detail.html", {
        'item': item,
        'related_items': related_items,
        })

@login_required
def New_Item(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            ''' doesnt save yet because it lacks the created_by field '''
            item = form.save(commit=False)
            item.created_by = request.user
            item.is_sold = False
            item.save()

            return redirect('item:detail', pk=item.id)
    else: 
        form = NewItemForm()

    return render(request, 'item/item_form.html', {
        'form': form,
        'title': 'New Item'
    })

@login_required
def Edit_Item(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=item.id)
    else: 
        form = EditItemForm(instance=item)

    return render(request, 'item/item_form.html', {
        'form': form,
        'title': 'Edit Item'
    })


@login_required
def Delete(request, pk): 
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:dashboard')

puddle/item/templates/item/detail.html
{% extends "core/base.html"%}

{% block title %} {{item.name}}  {% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6 mt-4 px-4">
    <div class="col-span-3">
        <img src="{{item.item_image.url}}" alt="" class="rounded-xl">
    </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="text-3xl mb-6">{{item.name}}</h1>
        <p class="text-gray-700">
            <strong>Price: </strong> GHc {{item.price}}
        </p>
        <p class="text-gray-700">
            <strong>Seller: </strong>{{item.created_by}}
        </p>

        {% if item.description%}
        <p class="text-gray-500"><strong class="text-gray-700">Description: </strong> <br> {{item.description}}</p>
        {% endif%}


        {% if  item.created_by == request.user%}
        <div class="mt-6 p-6 bg-white rounded-xl">
            <p>This is your item!</p>

            <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-white text-lg font-semibold bg-teal-500 rounded-xl">Edit</a>

            <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-white text-lg font-semibold bg-red-500 rounded-xl">Delete</a>
        </div>
        {% else %}
        <a href="{% url 'conversation:new' item.id %}" class="inline-block py-3 px-6 mt-6 font-semibold text-white text-lg bg-teal-500 hover:bg-teal-700 rounded-xl">Contact Seller</a>
        {% endif %}
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Related Items</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for item in related_items %}
        <div class="aspect-ratio">
            <a href="{% url 'item:detail' item.id %}" class="">
                <div>
                    <img src="{{ item.item_image.url }}" alt="" class="rounded-t-xl">
                </div>
                
            
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{item.name}}</h2>
                    <p text-gray-500>Price: GHc {{item.price}}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

puddle/item/templates/item/item.html
{% extends 'core/base.html' %}

{% block title%}Browse Items {% endblock %}

{% block content%}
<div class="p-6 m-6 grid grid-cols-4 rounded-xl gap-4 bg-gray-100 ">
    <div>
        <form action="{% url 'item:item_view' %}">
            <input name="query" type="text" value="{{query}}"  placeholder="Search for an item" class="w-full rounded-xl py-4 px-2 border outline-gray-500">

            <button class="mt-2 px-8 py-4 text-white bg-teal-500 text-lg rounded-xl">Search</button>
        </form>
        
        <hr class="my-6">
        <p class="font-semibold">Categories</p>

        <ul>
            {% for category in categories%}
                <li class="py-2 px-2 rounded-xl {% if category.id == category_id %} bg-gray-200 {% endif %}">
                    <a href="{% url 'item:item_view'%}?query={{query}}&category={{category.id}}">{{category.name}}</a>
                </li>
            {% endfor %}
        </ul>


        <p class="font-semibold mt-4">Clear filters</p>
        <a href="{% url 'item:item_view' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a>


    </div>

    <div class="col-span-3">
        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
            <div class="aspect-ratio">
                <a href="{% url 'item:detail' item.id %}" class="">
                    <div>
                        <img src="{{ item.item_image.url }}" alt="" class="rounded-t-xl">
                    </div>
                    
                
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{item.name}}</h2>
                        <p text-gray-500>Price: GHc {{item.price}}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock%}

puddle/item/templates/item/item_form.html
{% extends 'core/base.html'%}

{% block title%} {{title}} {% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl font-semibold p-4">{{title}}</h1>

<form action="." method="post" enctype="multipart/form-data">
    {%csrf_token%}

    <div class="space-y-4 p-4">
        {{form.as_p}}
    </div>


    
    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form%}
                {{field.errors}}
            {% endfor %}

            {{form.non_field_errors}}
        </div>
    {% endif %}

    <button class="px-10 mt-4 ml-4 py-3 text-lg  bg-teal-500 hover:bg-teal-700 text-white rounded-xl">Submit</button>

</form>
{% endblock %}